DROP TABLE IF EXISTS subscription_events;
DROP TABLE IF EXISTS subscription_payments;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS pricing_plans;

CREATE TABLE pricing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    yearly_price NUMERIC(15,2) NOT NULL,
    student_cap INTEGER NOT NULL,
    trial_days_default INTEGER NOT NULL,
    grace_period_days_default INTEGER NOT NULL,
    warning_threshold_percent INTEGER NOT NULL,
    critical_threshold_percent INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_pricing_yearly_price_non_negative CHECK (yearly_price >= 0),
    CONSTRAINT chk_pricing_student_cap_positive CHECK (student_cap > 0),
    CONSTRAINT chk_pricing_warning_range CHECK (warning_threshold_percent >= 0 AND warning_threshold_percent <= 100),
    CONSTRAINT chk_pricing_critical_range CHECK (critical_threshold_percent >= 0 AND critical_threshold_percent <= 100),
    CONSTRAINT chk_pricing_threshold_order CHECK (warning_threshold_percent < critical_threshold_percent)
);

CREATE UNIQUE INDEX uk_pricing_plans_name ON pricing_plans (name);
CREATE INDEX idx_pricing_plan_active ON pricing_plans (active);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    pricing_plan_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    trial_end_date DATE,
    expiry_date DATE,
    grace_period_days INTEGER NOT NULL,
    version BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_subscription_school FOREIGN KEY (school_id) REFERENCES schools(id),
    CONSTRAINT fk_subscription_plan FOREIGN KEY (pricing_plan_id) REFERENCES pricing_plans(id),
    CONSTRAINT chk_subscription_status CHECK (status IN ('TRIAL','ACTIVE','PAST_DUE','SUSPENDED')),
    CONSTRAINT chk_subscription_grace_non_negative CHECK (grace_period_days >= 0)
);

CREATE INDEX idx_subscription_school_id ON subscriptions (school_id);
CREATE INDEX idx_subscription_status ON subscriptions (status);

CREATE TABLE subscription_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    subscription_id BIGINT NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    type VARCHAR(30) NOT NULL,
    payment_date DATE NOT NULL,
    reference_number VARCHAR(255),
    notes VARCHAR(1000),
    recorded_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_subscription_payment_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id),
    CONSTRAINT chk_subscription_payment_amount_non_negative CHECK (amount >= 0),
    CONSTRAINT chk_subscription_payment_type CHECK (type IN ('PAYMENT','UPGRADE_PRORATION')),
    CONSTRAINT uk_subscription_payment_reference UNIQUE (subscription_id, reference_number)
);

CREATE INDEX idx_subscription_payment_sub_payment_date ON subscription_payments (subscription_id, payment_date);

CREATE TABLE subscription_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    days_added INTEGER,
    previous_expiry_date DATE,
    new_expiry_date DATE,
    previous_status VARCHAR(20),
    new_status VARCHAR(20),
    reason VARCHAR(500),
    performed_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_subscription_event_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id),
    CONSTRAINT chk_subscription_event_type CHECK (type IN ('TRIAL_EXTENDED','SUBSCRIPTION_EXTENDED','PLAN_UPGRADED','MANUAL_SUSPENDED','MANUAL_REACTIVATED')),
    CONSTRAINT chk_subscription_event_prev_status CHECK (previous_status IS NULL OR previous_status IN ('TRIAL','ACTIVE','PAST_DUE','SUSPENDED')),
    CONSTRAINT chk_subscription_event_new_status CHECK (new_status IS NULL OR new_status IN ('TRIAL','ACTIVE','PAST_DUE','SUSPENDED'))
);

CREATE INDEX idx_subscription_event_subscription_id ON subscription_events (subscription_id);
